from fastapi import FastAPI
from pydantic import BaseModel
import smtplib
from email.message import EmailMessage

app = FastAPI()

# =====================
# CONFIG (TEMPORARY)
# =====================
SENDER_EMAIL = "sreeyashana4@gmail.com"
RECEIVER_EMAIL = "sreeyashana4@gmail.com"
APP_PASSWORD = "YOUR_GMAIL_APP_PASSWORD"  # not normal password

# =====================
# REQUEST SCHEMA
# =====================
class ReportPayload(BaseModel):
    case_id: str
    username: str
    tweet_id: str
    tweet_text: str
    confidence: float
    risk: str

# =====================
# SEND REPORT ENDPOINT
# =====================
@app.post("/send-report")
def send_report(data: ReportPayload):

    msg = EmailMessage()
    msg["Subject"] = f"[SafeX Guard] Cyberbullying Report — {data.case_id}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL

    msg.set_content(f"""
Hello,

A cyberbullying case has been detected and reviewed.

--- Case Details ---
Case ID: {data.case_id}
Account: {data.username}
Tweet ID: {data.tweet_id}
Risk Level: {data.risk}
Confidence: {data.confidence}

Tweet Text:
"{data.tweet_text}"

This report was generated by SafeX Guard (Demo Phase).

Regards,
SafeX Guard System
""")

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(SENDER_EMAIL, APP_PASSWORD)
            smtp.send_message(msg)

        return {"status": "success", "message": "Report email sent"}

    except Exception as e:
        return {"status": "error", "message": str(e)}
